### ISSUE TITLE
Inform User that JavaFX is required if they don't have it on boot.

### ISSUE THREAD

**Issue by dranorter** [DraqueT/PolyGlot#248]
I tried this out in Windows 7 and found that the "Lexicon" and "Quick Entry" buttons don't do anything; the others seem to work. But then, the work computers all have Java 5 so I figured I'd try it out at home. The same thing happened! I'm using openjdk Java 7 on Ubuntu 14.04.

The command line gives "Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel" as well as "Exception in thread "Thread-0" java.lang.NoSuchMethodError: java.util.Map.replace(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;". However, the NoSuchMethodError shows up on many actions which apparently work, such as opening "Grammar". I googled it and it appears Map.replace doesn't exist in Java 7.

It does look like everything works fine in jre 1.8.0 downloaded from Oracle.

**Comment by DraqueT** [comment]
Yup, you're right! In future versions, I'm going to have it run a check and inform the user of this and that they must upgrade to use it.

**Comment by WovenTales** [comment]
I'm not completely sure that's the problem, or at least the only problem. I'm running Arch Linux and have the current Java package for that distro (version output below, though I suppose my problems might be due to openjdk), and I'm still running into what might be the same error. I've pasted the terminal output below; I'm sure that at least some of these would be better in a new issue, but I'm not completely sure which so I'll just put them all here.
```
$ java -version
openjdk version "1.8.0_60"
OpenJDK Runtime Environment (build 1.8.0_60-b24)
OpenJDK 64-Bit Server VM (build 25.60-b23, mixed mode)
```

On startup, seemingly due to the splash screen (which otherwise renders just fine):
```
libpng warning: iCCP: known incorrect sRGB profile
```

On clicking "Lexicon":
```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/scene/Parent
        at PolyGlot.Screens.ScrDictMenu.lexHit(ScrDictMenu.java:661)
        at PolyGlot.Screens.ScrDictMenu.btnLexiconActionPerformed(ScrDictMenu.java:1160)
        at PolyGlot.Screens.ScrDictMenu.access$500(ScrDictMenu.java:65)
        at PolyGlot.Screens.ScrDictMenu$5.actionPerformed(ScrDictMenu.java:936)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6535)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6300)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4891)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: javafx.scene.Parent
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 40 more
```

On clicking "Quickentry":
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at PolyGlot.Screens.ScrDictMenu.quickEntryHit(ScrDictMenu.java:681)
        at PolyGlot.Screens.ScrDictMenu.btnQuickEntryActionPerformed(ScrDictMenu.java:1174)
        at PolyGlot.Screens.ScrDictMenu.access$1000(ScrDictMenu.java:65)
        at PolyGlot.Screens.ScrDictMenu$10.actionPerformed(ScrDictMenu.java:971)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6535)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6300)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4891)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by DraqueT** [comment]
You're right, I had thought that what I was using was compatible with J7, but it seems like you need at least J8 to run it! When I get back to this project again, that will be updated for sure. It seems like JFX has a few libraries that are J8 only. Thank you for the feedback and the stack traces there! Those are always really helpful. ^^

**Comment by DraqueT** [comment]
Ack, just read the first message again. X|

Oof... I'm gonna have to spool up an Arch Linux machine at some point to address this. Again though, thanks for the feedback!

**Comment by dranorter** [comment]
WovenTales, I have not used Arch Linux myself but: is the javafx stuff perhaps packaged separately from openjdk? Do you have the package java-openjfx installed?

**Comment by WovenTales** [comment]
Aha! That's the problem. Thanks! I've installed javafx (which is called java-openjfx on Arch) in addition to Java 8, and that's solved the problems with those dialogs. Still have the libpng warning, but that seems reasonably harmless.

**Comment by DraqueT** [comment]
Thanks for the help here, guys! I'm going to be adding in boot testing to make certain that the user has JavaFX installed, which will inform the user if they do not have it. I know it's been a bit since I updated PolyGlot, but I'm going to be getting back to it sooner or later. ^^

**Comment by DraqueT** [comment]
Corrected.
